all:
	@echo '[XELATEX]'
	@xelatex -shell-escape logo.tex > /dev/null
	@echo '[MV]'
	@mv logo-0.png ../eyolfson_website/static/img/logo.png

	@echo '[XELATEX]'
	@xelatex -shell-escape favicon.tex > /dev/null
